# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userext',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='userext',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='birthday',
            field=models.DateTimeField(blank=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='logintime',
            field=models.DateTimeField(verbose_name='登陆时间'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='nickname',
            field=models.CharField(max_length=64, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='realname',
            field=models.CharField(max_length=64, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='score',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='status',
            field=models.IntegerField(default=0, verbose_name='账号状态'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='validkey',
            field=models.CharField(max_length=256, verbose_name='验证key'),
        ),
    ]
