# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('independentarticle', '0002_auto_20171012_2109'),
        ('article', '0002_auto_20170924_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('independentarticle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='independentarticle.Independentarticle')),
            ],
        ),
    ]
