# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='independentarticle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='independentarticle.Independentarticle'),
        ),
    ]
