# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20171014_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='所属文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='independentarticle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='independentarticle.Independentarticle', verbose_name='所属独立文章'),
        ),
    ]
