# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('independentarticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '独立文章分类名称', 'verbose_name_plural': '独立文章分类名称'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '独立文章标签名称', 'verbose_name_plural': '独立文章标签名称'},
        ),
    ]
