# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visit_day', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('Visitors_number', models.PositiveIntegerField(default=0, verbose_name='访问人数')),
            ],
            options={
                'verbose_name': '访客统计',
                'ordering': ['-Visit_day'],
                'verbose_name_plural': '访客量统计',
            },
        ),
    ]
