# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='Visit_day',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
